name = "Twilight.hugo"
license = "MIT"
licenselink = "https://github.com/ILikePizza555/Twilight.hugo/blob/master/LICENSE"
description = "The hugo theme I use for my personal site"
homepage = "https://github.com/ILikePizza555/Twilight.hugo"
tags = []
features = []
min_version = 0.30

[author]
  name = "Isaac Avram"
  homepage = "http://avrisaac.com"